name: Build AMPOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose run --rm build
        # language=bash
      - run: |
          if [ -f "out/ampos.iso" ]; then
            echo "✅ ISO file found - build successful."
          else
            echo "❌ ISO file not found - build is likely broken."
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: AMPOS ISO File
          path: out/ampos.iso
